version: "3.10"
services:
  rabbitmq:
    image: "rabbitmq:3.11-management"
    deploy:
      mode: global
    ports:
      - "5672:5672"
      - "15672:15672"
  dispatcher:
    image: "dcn:latest"
    deploy:
      mode: global
    ports:
      - "9999:9999"
    command: ["python", "service/dispatcher.py", "rabbitmq"]
    volumes:
      - ./log/dispatcher/:/src/log/dispatcher/
    depends_on:
      - rabbitmq
  agent:
    image: "dcn:latest"
    command: ["python", "service/agent.py", "dispatcher", "docker"]
    volumes:
      - ./log/agent/:/src/log/agent/
    depends_on:
      - dispatcher
    deploy:
      mode: replicated
      replicas: 1
